title: 'Divine DevOps'
name: 'Divine DevOps'
description: 'A parody universe blending humor, tech, religious themes and lore with DevOps culture.'
author: 'divinedevops@poopnet.info'
baseurl: '/divine-devops'
url: 'https://anthonypdawson.github.io'
theme: minima
# theme: jekyll-theme-console
layout: terminal_post
sass:
    sass_dir: _sass
    style: 'compressed'
    sourcemap: 'development'
collections:
  future:
    output: true
    permalink: /future/:name/
plugins:
    - jekyll-feed
    - jekyll-sitemap
include:
    - _redirects
    - robots.txt
    - sitemap.xml
exclude:
    - vendor
    - node_modules
    - '_unpublished'
    - 'README.md'
    - '*.sh'
    - '*.yml'
    - '*.json'
    - 'Gemfile*'
    - '*.bak'
    - 'scripts'
