title: 'Divine DevOps Universe'
description: 'A parody universe blending religious lore with DevOps culture.'
baseurl: '/divine-devops'
url: 'https://anthonypdawson.github.io'
theme: minima
# theme: jekyll-theme-console
layout: terminal_post
plugins:
    - jekyll-feed
    - jekyll-sitemap
include:
    - _redirects
exclude: 
    - vendor
    - '_future'
    - '_unpublished'
    - 'README.md'
    - '*.sh'
    - '*.yml'
    - '*.json'
    - 'Gemfile*'
    - '*.bak'
