title: 'Divine DevOps'
name: 'Divine DevOps'
description: 'A parody universe blending humor, tech, religious themes and lore with DevOps culture.'
author: 'divinedevops@poopnet.info'
baseurl: '/divine-devops'
url: 'https://anthonypdawson.github.io'
theme: minima
# theme: jekyll-theme-console
layout: terminal_post
sass:
    sass_dir: _sass
    style: compact
    css_dir: assets/css
    sourcemap: true
    sass_options:
        style: compressed
        sourcemap: true
        cache: false
        quiet: true
        load_paths:
        - _sass
        - /assets/css
plugins:
    - jekyll-feed
    - jekyll-sitemap
include:
    - _redirects
    - robots.txt
    - sitemap.xml
exclude:
    - vendor
    - '_future'
    - '_unpublished'
    - 'README.md'
    - '*.sh'
    - '*.yml'
    - '*.json'
    - 'Gemfile*'
    - '*.bak'
    - 'scripts'
