[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]


# Uncomment and customize for custom domains
#[[headers]]
#  for = "/assets/*"
#  [headers.values]
#    Cache-Control = "public, max-age=31536000"

# Add more settings as needed for plugins, environment variables, or redirects.
