[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[functions]
directory = "netlify/functions"

[[redirects]]
  from = "/random"
  to = "/netlify/functions/random-post"
  status = 200

# Uncomment and customize for custom domains
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Add more settings as needed for plugins, environment variables, or redirects.

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-sitemap"
