name: Deploy Redirect to GitHub Pages and Trigger Netlify Build
on:
  push:
    branches:
      - main
    paths:
      - '.github/gh-pages-redirect.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy redirect file
        run: cp .github/gh-pages-redirect.html index.html
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true

