name: Deploy Redirect to GitHub Pages and Trigger Netlify Build
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *' # Runs daily at 9:00 UTC
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy redirect file
        run: cp .github/gh-pages-redirect.html index.html
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true

  netlify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST "https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}"
